### ISSUE TITLE
Un-weight artists without much music

### ISSUE THREAD

**Issue by treyhunner** [FreeMusicNinja/api.freemusic.ninja#2]
Artists who who don't have a full CC album should be noted as less important (marked as dormant, zombie, or a better term).

We could search the FreeMusicArchive API and find artists without albums like this:

`http://freemusicarchive.org/api/get/albums.json?api_key=<key>&artist_id=2908`

Maybe we could create a model to store API responses for FreeMusicArchive artist albums or tracks. We could hide/disable artists with less than three tracks.

From FreeMusicNinja/freemusic.ninja#19

**Comment by macro1** [comment]
Track count can now be stored in artists.Hyperlink. Rather than 'un-weight' artists, we're highlighting artists we know have at least 3 tracks. The results will improve as the data collection efforts (#28, #24) are underway.
