### ISSUE TITLE
Kristin Hersh missing from artist results

### ISSUE THREAD

**Issue by treyhunner** [FreeMusicNinja/api.freemusic.ninja#41]
When searching for `Kristin Hersh`, `Kristin Hersh` is not shown at all.

[See API results without Kristin Hersh](http://api.freemusic.ninja/artists/?name=Kristin+Hersh)

[See Kristin Hersh artist result](http://api.freemusic.ninja/artists/40008/)

My best guess is that it's because she has `null` tracks on Bandcamp.

**Comment by macro1** [comment]
Thanks for adding it to the issues, I think I would have forgotten about it. I'll look at it this evening.
